### ISSUE TITLE
Binary name

### ISSUE THREAD

**Issue by fossfreedom** [linuxmint/lightdm-settings#10]
At the moment the Debian binary name is lightdm-settings ... And this binary writes config for slick greeter. Feels kind of confused.

If in the future it is extended to the gtk greeter would the app being run basically consist of tabs named slick/gtk/etc or would there be one binary for each greeter configurator? i.e. the binary for slick could/should be instead slick-settings or possibly lightdm-slick-settings.

**Comment by clefebvre** [comment]
I think it should be able to support multiple greeters going forward. Ideally, to detect which one is in use and provide configuration for this one.

It already started to support lightdm's core configuration as well and it probably will be extended in that regard going forward. For instance, we'd like users to be able to set autologin options, that's a feature they had with mdmsetup in the past.
