### ISSUE TITLE
[Feature Request] Numlock On/Off

### ISSUE THREAD

**Issue by kelebek333** [linuxmint/lightdm-settings#14]
Hi development team,

Could you add numlock on/off feature to LightDM Settings.

Best regards.

**Comment by DorianB2017** [comment]
Thank you Clem for your reply to my comment (No.78 - http://blog.linuxmint.com/?p=3306#comment-136442) and I wait impatiently the Numlock option in the Login Window window of Linux Mint 18.2 "Sonya" Cinnamon Edition with LightDM.
I really like Linux Mint.
Thank you for everything and best regards.

**Comment by clefebvre** [comment]
Yes, it was added to the roadmap so we'll consider it this cycle. Closing this issue for now.
