### ISSUE TITLE
draw-user-backgrounds entry needs to be defined

### ISSUE THREAD

**Issue by oberon-manjaro** [linuxmint/lightdm-settings#23]
As investigated [here](https://github.com/linuxmint/slick-greeter/issues/80#issuecomment-386915616) , Cinnamon will use the current desktop background for **slick-greeter** unless
`draw-user-backgrounds=false` is explicitly defined in **/etc/lightdm/slick-greeter.conf**.
Currently this settings isn't available in **lightdm-settings** dialog and needs to be added manually in an auto-created config file to make the background setting work and override user-background.

**Comment by oberon-manjaro** [comment]
It appears somehow 
[should_show_user_bg_switch](https://github.com/linuxmint/lightdm-settings/blob/master/usr/lib/lightdm-settings/lightdm-settings#L366) isn't working properly or a different strategy will be needed.
In my case on Manjarolinux I have no entry for 'user-background' while at the same time as explained above, I need the property defined in the config to stop slick-greeter from using Cinnamon's user background.

**Comment by oberon-manjaro** [comment]
In **slick-greeter** [x.dm.slick-greeter draw-user-backgrounds](https://github.com/linuxmint/slick-greeter/blob/master/data/x.dm.slick-greeter.gschema.xml#L12) defaults to `true` and this setting is being respected in a Cinnamon environment, maybe depending on os-release...?
Or maybe this is related to **accountsservice** version? On Archlinux based systems we are currently at **v0.6.47**

**Comment by mbirth** [comment]
![image](https://user-images.githubusercontent.com/130302/39679264-db0646d4-519a-11e8-8513-81c5f474446b.png)

EDIT: This is version `1.1.4-0ubuntu1`.

**Comment by oberon-manjaro** [comment]
Aah. I see only now that this has already been addressed with https://github.com/linuxmint/lightdm-settings/commit/88fe0974aff7caddecd3701062922feac95ca722
Seems we are just waiting for a new release for this to be fixed...
