### ISSUE TITLE
After recent changes to migrate at pkexec gui refuse to open

### ISSUE THREAD

**Issue by Ste74** [linuxmint/lightdm-settings#24]
Hi there, like the title say the gui wont start via a desktop interface but it work in a terminal via `pkexec lightdm-settings`. User report the issue in Budgie via Budgie menu and also in Cinnamon via `cinnamon-settings`..
OS Manjaro Linux 

Thank  you in advance for any tip
Stefano

**Comment by fossfreedom** [comment]
@Ste74 this is a budgie matter.  You can close this.  I've proposed a PR for this on the solus budgie-desktop github tracker.

**Comment by Ste74** [comment]
Ok @fossfreedom, thank you for your work
