### ISSUE TITLE
Errors upon Execution

### ISSUE THREAD

**Issue by ruppec** [linuxmint/lightdm-settings#27]
Could not load /etc/lightdm/slick-greeter.conf.
lightdm version: 1.26.0
Traceback (most recent call last):
  File "/usr/lib/lightdm-settings/lightdm-settings", line 45, in do_activate
    self.create_window()
  File "/usr/lib/lightdm-settings/lightdm-settings", line 154, in create_window
    row = SettingsRow(Gtk.Label(_("GTK theme")), SettingsCombo(keyfile, settings, "theme-name", self.get_gtk_themes(), "string", size_group))
  File "/usr/lib/lightdm-settings/SettingsWidgets.py", line 309, in __init__
    var_type = type(options[0][0])
IndexError: list index out of range

**Comment by Duder963** [comment]
I'm recieving a similar error on Arch Linux. Curiously, this is only happening on my desktop computer. My laptop loads the program just fine

**Comment by jtnegrotto** [comment]
The root cause is that lightdm-settings expects at least one GTK theme to be installed. I've submitted a PR, but for now you can just install a GTK theme and it will work, or you can patch `/usr/lib/lightdm-settings/SettingsWidget.py` yourself (it's a one-line change).
