### ISSUE TITLE
Use pkexec instead of gksu

### ISSUE THREAD

**Issue by ghost** [linuxmint/lightdm-settings#3]
_Greetings, before anything, I have read what you told to everyone involved on the bugs/issues in the [pull request here](https://github.com/linuxmint/mintsources/issues/75) (I am one of the guys involved in pointing some places)._

I have managed to port lightdm-settings on Arch, but I would like to ask if it is possible to make this package use pkexec, right now I have uploaded the package as is (and pulling gksu as a temporary dependency, since Arch doesn't have much packages that has it as a hard dependency); also I have tried to do some testing using [this policy file](https://pastebin.com/mVBpCKf6) and manually editing the executable file with no luck at all.

I do understand that it requires a lot of testing and quite possibly that you might want to do something on the Xapps library, but maybe we can start with some apps that we can help to port to pkexec step by step (I would like to help to port this one and I didn't want to upload it as is, but I just uploaded slick-greeter on Arch as well and I would like to at least have this one working as a configuration companion).

I also know that you might be running against the clock to test some other things related to the Mint and Cinnamon releases, but I would like to help, even if it is little

If I can do or try something, I am willing to do it even if it takes some time for me to answer

**Comment by clefebvre** [comment]
Hi @SamBurgos,

I don't mind switching lightdm-settings to pkexec individually. We can do that without waiting on a solution in xapp. Please make a PR if you want.

**Comment by ghost** [comment]
Understood and thanks for the advice, it might take a while since I need to read a lot on how to enable pkexec, and my previous tests hasn't ended up really well

EDIT: do you know any package that I can use as a reference to change settings from gksu to pkexec? So far I can't find any documentation on how to do that change on an executable script
