### ISSUE TITLE
No settings for timed login

### ISSUE THREAD

**Issue by jelabarre59** [linuxmint/lightdm-settings#31]
The older login managers (GDM, MDM) used to have a setting to set timed logins for users (autologin after a configured wait time, not immediately logging in).  LightDM is still missing this setting, which is a problem now that it is being pushed as the replacement for MDM and GDM (a replacement that is lacking functionality that it's predecessor had).  

The short-term workaround is to manually edit the greeter's config file, but the documentation to do so is sorely lacking (or even outright missing).

**Comment by leigh123linux** [comment]
@jelabarre59  Perhaps you should have googled lightdm 

https://wiki.ubuntu.com/LightDM#Setting_an_Automatic_Login

Normally you would edit lightdm.conf to do this, to check config run

```
$ lightdm --show-config
   [Seat:*]
B  allow-guest=false
D  session-wrapper=/etc/X11/xinit/Xsession
F  xserver-command=X -core -noreset
G  greeter-session=slick-greeter

   [LightDM]
C  minimum-vt=1
E  user-authority-in-system-dir=true

Sources:
A  /usr/share/lightdm/lightdm.conf.d/50-backup-logs.conf
B  /usr/share/lightdm/lightdm.conf.d/50-disable-guest.conf
C  /usr/share/lightdm/lightdm.conf.d/50-minimum-vt.conf
D  /usr/share/lightdm/lightdm.conf.d/50-session-wrapper.conf
E  /usr/share/lightdm/lightdm.conf.d/50-user-authority-in-system-dir.conf
F  /usr/share/lightdm/lightdm.conf.d/50-xserver-command.conf
G  /usr/share/lightdm/lightdm.conf.d/90-slick-greeter.conf
H  /etc/lightdm/lightdm.conf
```

**Comment by jelabarre59** [comment]
I'm looking at the 1.1.4-0ubuntu1 version of this (Linux Mint 19.1) and this is still missing.  This was a standard feature in GDM and MDM (which both had options for setting timed logins), yet LightDM's settings GUI is still missing this.  Considering LightDM is the replacement for those, it should at least have functional parity to what it is intended to replace.

**Comment by shanmukhateja** [comment]
@leigh123linux I believe @jelabarre59 is trying to mention the fact we do not have GUI way to accomplish delayed login even though the config file supports the feature.
