### ISSUE TITLE
Version number error

### ISSUE THREAD

**Issue by algent-al** [linuxmint/lightdm-settings#42]
Updated the package to newest version 1.3.1 but running it from terminal still show
`lightdm version: 1.30.0`
![ldms](https://user-images.githubusercontent.com/46356616/69944506-c72f7b00-14e7-11ea-8b3e-a6c5aa9ca7f1.png)

**Comment by leigh123linux** [comment]
The command displays the lightdm version not lightdm-settings.

```
$ lightdm --version
lightdm 1.30.0
```
