### ISSUE TITLE
Appearance/Background/Background problem

### ISSUE THREAD

**Issue by zcx2020** [linuxmint/lightdm-settings#43]
I have two LM-19.3 Cinnamon x64 machines here.  Both have been upgraded from 19.1 -> 19.2 -> 19.3.  Both fully up to date.

Both have user desktop backgrounds selected from LM selections.  Both have defaults set in lightdm-settings, in particular Draw user background is ON.

When I start up lightdm-settings I get this message on both machines...

$ sudo lightdm-settings
$ Could not load /etc/lightdm/lightdm.conf.
lightdm version: 1.26.0

On machine A setting  Draw user background set to OFF works correctly. 

On machine B the pre-login default background has changed (apparently spontaneously) to /usr/share/backgrounds/linuxmint/default_background.jpg, even though Draw user background is still set to ON.

As a workaround I have redirected the /usr/share/backgrounds/linuxmint/default_background.jpg link to the user desktop file in /usr/share/backgrounds/linuxmint-tessa folder, set this as the background in lightdm-settings and set Draw user background to OFF.

Is there something else in the configuration that could have changed?

**Comment by clefebvre** [comment]
That's the way it's supposed to work. If draw user backgrounds is disabled, it shows the background set as background to all users (and that by default points to /usr/share/backgrounds/linuxmint/default_background.jpg). If it's enabled it shows the selected user's background.
