### ISSUE TITLE
Graphics issue

### ISSUE THREAD

**Issue by aaditya4u** [linuxmint/lightdm-settings#46]
I have no clue is it light dm or nvidia but please hear me out.
Hardware details
dell xps 15 9550 
i7 with 32 gb ram 1 tb ssd gforce 960m nvidia gpu

issue is i tried with mint 19 cinnmon 64bit os first
os is awesome however nvidia support sucks. graphics is constant freezing and flickering on any video playback such as movies, youtube. small flickering however noticable. graphical process are being slow.

in lmde 4 i have installed now and runs everything smothly. when i installed nvidia was not installed however i choose to install nvidia version while os installation. after that i had to go to no gui mode and update everything to get nvidia on board. and os runs super smooth like windows. no issues with graphics.

i thought i have lightdm issue but i am new to linux so you decide whats the issue

Issues..

1) why mint 19 doesnt have same smooth graphics like lmde 4
2) when lmde 4 is stable why it didnt load nvidia why installation 
3) my nvidia xserver app is not loading atall. 
4) how to make nvidia prime rather than intel like for vga too not only 3d support.

please fix this all and help me

**Comment by leigh123linux** [comment]
Sorry try asking on a  forum instead.
