### ISSUE TITLE
settings not opening

### ISSUE THREAD

**Issue by aviumcaravan** [linuxmint/lightdm-settings#47]
not much to say, i get this error:

```
(lightdm-settings:11268): GLib-GIO-ERROR **: 14:15:12.819: Settings schema 'x.dm.slick-greeter' does not contain a key named 'stretch-background-across-monitors'
```

how could i potentially fix this?

**Comment by claudiux** [comment]
@wiktornowicki Please try the command: `sudo lightdm-settings` in a terminal and report here its output.


Using `dconf-editor`, check if the 'stretch-background-across-monitors' key exists.

![Capture d’écran du 2020-08-26 15-51-38](https://user-images.githubusercontent.com/33965039/91312088-1f17bb80-e7b4-11ea-8e9b-10697954c79a.png)

**Comment by claudiux** [comment]
@wiktornowicki Any news?

**Comment by aviumcaravan** [comment]
well, as it turns out, the best way to install it was pulling a package from a different distro, probably a compilation error on my build

**Comment by claudiux** [comment]
So, maybe you can close this issue?

**Comment by mireiner** [comment]
The same issue on my Arch Linux system with KDE Plasma 20.2 desktop environment:
After starting lightdm-settings from KDE Plasma menu entry and entering/confirming the password dialogbox lighdm-settings window doesn't open.
But the command in terminal "sudo lightdm-settings" works fine.

**Comment by clefebvre** [comment]
Make sure you've got slick-greeter 1.4.0 or greater.

**Comment by yamanidev** [comment]
Hello,
I am having the same issue with a slightly different error message (I too could not open Login Window GUI, so I resorted to the terminal way using `sudo lightdm-settings` which gave me this output:
```Could not load /etc/lightdm/lightdm.conf.
lightdm version: 1.30.0

(lightdm-settings:5797): GLib-GIO-ERROR **: 00:14:11.995: Settings schema 'x.dm.slick-greeter' does not contain a key named 'clock-format'
````
I'd appreciate any help I can get. Have a nice day.
