### ISSUE TITLE
Resolution resets itself

### ISSUE THREAD

**Issue by Aurum420** [linuxmint/lightdm-settings#48]
Most of my computers are headless and I access via Nomachine. When I open Display and change the Resolution from 1920 x 1080 (16:9) Recommended to 1600 x 900 (15:9) and then click Apply. The resolution changes and I click popup "Keep These Settings."
The next time I log in via Nomachine the resolution has rest to 1920 x 1080 and is again too big to fit on my monitor.
Please make the Resolution I set persist. TIA

**Comment by clefebvre** [comment]
I assume you're talking about the login screen, it's not part of your user session and thus doesn't follow your display configuration.

**Comment by Aurum420** [comment]
I'm not talking about the login screen. I'm talking about the desktop.
