### ISSUE TITLE
Can't edit the login window - Linux Mint 20 Ulyana Mate

### ISSUE THREAD

**Issue by danindenver** [linuxmint/lightdm-settings#50]
Can't edit the login window - Linux Mint 20 Ulyana Mate

System:
Kernel: 5.4.0-81-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 
Desktop: MATE 1.24.0 wm: marco dm: LightDM 
Distro: Linux Mint 20 Ulyana base: Ubuntu 20.04 focal

Steps to reproduce:
Control Center>Administration>Login Window
Click Login Window
Enter password
Nothing happens

Posted here:
https://forums.linuxmint.com/viewtopic.php?p=2057905&sid=8fc94f65551d685a4500bbf8998c3313#p2057905

Most recent reponse:
by ren09 » Tue Aug 24, 2021 2:15 am
It is a bug in lightdm-settings 1.5.5(ulyana). Have updated the other 3 lightdm issues and the settings-window pops up and works.
lightdm-settings 1.3.3+dfsg.1-1 (focal) doesn't have the bug and works. But after updating lightdm-gobject-1-0 the window pops up and need 10sec to be ready.
Not only with Mate, have Cinnamon. The desktop starts later than the login window!

**Comment by clefebvre** [comment]
https://github.com/linuxmint/lightdm-settings/issues/51
