### ISSUE TITLE
lightdm-settings is not opening (neither with GUI nor with Terminal)

### ISSUE THREAD

**Issue by yamanidev** [linuxmint/lightdm-settings#51]
Hello,
I am having an issue with starting lightdm-settings also known as Login Window (GUI) on my Linux Mint OS. So resorted to the terminal way using `sudo lightdm-settings` which gave me this output:
```Could not load /etc/lightdm/lightdm.conf.
lightdm version: 1.30.0

(lightdm-settings:5797): GLib-GIO-ERROR **: 00:14:11.995: Settings schema 'x.dm.slick-greeter' does not contain a key named 'clock-format'
````
I've also tried using `dconf-editor` as suggested in this [issue](https://github.com/linuxmint/lightdm-settings/issues/47)), but I did not find the "clock-format" key. Any ideas?

I'd appreciate any help I can get. Have a nice day.

**Comment by ghost** [comment]
I am currently getting the same issue.

**Comment by link0ff** [comment]
A workaround is to ensure that the file `/etc/lightdm/slick-greeter.conf` contains at least these lines:

```
[Greeter]
clock-format=%H:%M
```

**Comment by yamanidev** [comment]
@link0ff that works like a charm thank you! 
Though this displays `Could not load /etc/lightdm/lightdm.conf.`

**Comment by MobiZaman** [comment]
> 

I am having the same issue. I have tried all the solutions mentioned on the web, but to no avail. 
I don't even have a file of the name "slick-greeter.conf". But I do have these:
lightdm.conf  
lightdm.conf.d  
lightdm-gtk-greeter.conf.d  
users.conf
I added the clock-format line in lightdm.conf, but that didn't work as well.

**Comment by MobiZaman** [comment]
> > 
> 
> I am having the same issue. I have tried all the solutions mentioned on the web, but to no avail. I don't even have a file of the name "slick-greeter.conf". But I do have these: lightdm.conf lightdm.conf.d lightdm-gtk-greeter.conf.d users.conf I added the clock-format line in lightdm.conf, but that didn't work as well.

Actually I realized that I needed to create a new file named slick-greeter.conf. So I created it with this:
`sudo xed /etc/lightdm/slick-greeter.conf`
and pasted the following lines into it:
```
[Greeter]
clock-format=%H:%M
```
After this, the `sudo lightdm-settings` command worked and opened the Login Window.

**Comment by clefebvre** [comment]
Make sure you have slick-greeter 1.5.0 or newer installed.

https://github.com/linuxmint/slick-greeter/commit/397070806984372ed5ecec2b639c471fd01ab1c5

**Comment by clefebvre** [comment]
This was an issue on our side, triggered by a backport of lightdm-settings in Mint 20. It's fixed now. We backported slick-greeter 1.5.2 into Mint 20 today.
