### ISSUE TITLE
How does one turn this on (in Cinnamon 3.4), please?

### ISSUE THREAD

**Issue by ghost** [linuxmint/lightdm-settings#6]
Not seeing any 'wizard'ish way to turn on the new logon screen, I installed and setup the lightdm package. Upon reboot, a fair amount of brokenness ensued - first I couldn't log in, but got an error; then the error went away, but I was left with a blank screen; now I can login, and the new greeter looks good, but the old login screen pops up briefly, and the new login screen says 'Ubuntu'. Moreover, I thought there was meant to be an option in System Settings to configure the new logon screen - but I can't find it.

**Comment by leigh123linux** [comment]
Did you run?

```
dpkg-reconfigure lightdm
```

**Comment by leigh123linux** [comment]
Your issue isn't related to lightdm-settings as it's just a configuration for slick-greeter.
Unless ubuntu provides something to reconfigure lightdm your out of luck.

https://wiki.ubuntu.com/LightDM

**Comment by clefebvre** [comment]
Make sure you only have one DM installed (remove MDM if you switched to LightDM). Also make sure you have slick-greeter installed.. and then you can configure it with this tool.

**Comment by ghost** [comment]
Dear all

Thank you. My problem was that I did not have slick-greeter installed. Still - and mainly because my desktop icons were not all showing (and I filed a separate bug report about that) - I've removed all Cinnamon 3.4 stuff from my machine. The removal seems to have left me with very high Cinnamon CPU usage, but I'll figure out how to fix that, I think.
