### ISSUE TITLE
Background at login window keeps reverting to default

### ISSUE THREAD

**Issue by emirvmendoza** [linuxmint/lightdm-settings#63]
### Distribution

LMDE 6

### Package version

6.0.4

### Frequency

Always

### Bug description

Custom background appears for only one second before reverting to default

### Steps to reproduce

1. System Settings > Login Window
2. Background > Choose background
3. Restart 

### Expected behavior

Chosen background stays permanently on login window

**Comment by clefebvre** [comment]
Please provide the following information:

- your version of lightdm-settings
- your version of slick-greeter
- the full path of the picture
- the permissions of the picture file
- whether or not your home directory is encrypted
- the permissions of your home directory

**Comment by emirvmendoza** [comment]
- your version of lightdm-settings: **2.0.2**
- your version of slick-greeter: **2.0.3+faye**
- the full path of the picture: **/usr/share/backgrounds/linuxmint/sele_ring_green.jpg**
- the permissions of the picture file:
**Owner: root 
Access: Read and write

Group: root
Access: Read-only

Access: Read-only**

- whether or not your home directory is encrypted: **Yes**
- the permissions of your home directory:
**Owner: (my username) 
Folder access: Create and delete files
File access: ---

Group: (my username)
Folder access: None
File access: ---

Folder access: None
File access: ---**

**Comment by clefebvre** [comment]
@emirvmendoza can you take a screenshot of your `Login Window` settings?

**Comment by emirvmendoza** [comment]
@clefebvre Please see screenshots.

![Screenshot from 2024-01-17 23-12-36](https://github.com/linuxmint/lightdm-settings/assets/154249992/ba1b75b9-7620-4db3-a70c-b361517ae928)
![Screenshot from 2024-01-17 23-12-43](https://github.com/linuxmint/lightdm-settings/assets/154249992/52c6faa7-77a4-46d4-a831-259816c25f47)
![Screenshot from 2024-01-17 23-12-47](https://github.com/linuxmint/lightdm-settings/assets/154249992/e3450402-e6e6-4c7a-b5d5-617f0fc7f059)

**Comment by clefebvre** [comment]
Thanks @emirvmendoza,

Disable this option: 

![image](https://github.com/linuxmint/lightdm-settings/assets/1138515/1a9fbefa-733b-4b64-931f-58d337fef5ce)

**Comment by emirvmendoza** [comment]
Works fine now.  Thank you, @clefebvre
