### ISSUE TITLE
Login Window Appearance tab doesn't have a scrollbar

### ISSUE THREAD

**Issue by emmanesgana** [linuxmint/lightdm-settings#64]
### Distribution

Linux Mint 21.3 Cinnamon

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

Intel Corporation UHD Graphics 620

### Frequency

Always

### Bug description

Login Window Appearance tab doesn't have a scrollbar to reach the bottom settings.

### Steps to reproduce

Menu > Search Login Window > Appearance tab

Scrollbar missing

### Expected behavior

Scrollbar should be available to reach the bottom settings.

**Comment by billyswong** [comment]
Same problem reported in this forum post. https://forums.linuxmint.com/viewtopic.php?t=416821

With more and more entries added to the configuration dialog, it is getting too tall for people with only 768px screen height.
