### ISSUE TITLE
High CPU usage if left by itself for a while

### ISSUE THREAD

**Issue by AndreiMiculita** [linuxmint/lightdm-settings#65]
Sometimes I turn on my laptop and let the boot process happen without interfering. It turns on and gets to the lightdm greeter.

I let it run without interfering and after a while the screen turns off (presumably to save energy).

After a while the CPU fans spin up. Moving the mouse (which turns the screen back on) solves this.

Could you look into this? Let me know what information you need for reproducing it.

OS: Linux Mint 21.2 x86_64
Kernel: 6.5.0-26-generic
DE: Cinnamon

**Comment by clefebvre** [comment]
Please use the forums or the chat room to help troubleshoot.

Note that lightdm-settings is only the settings tool.
