### ISSUE TITLE
User wallpaper doesn't appear

### ISSUE THREAD

**Issue by Luiz-Trindade** [linuxmint/lightdm-settings#66]
If the user adds an new wallpaper, that wallpaper doesn't appear in the lockscreen when the sytem boots up, only the wallpapers of linux mint are available by default. That's an issue, because the user will think that the system don't allow to change the wallpaper of the login screen. I have to do: "sudo gpasswd --add lightdm $USER" for fixing.. 

I would also like to suggest an addition for future versions: adding the option to change the login screen wallpaper.

**Comment by leigh123linux** [comment]
The wallpapers must be system wide, wallpapers in /home/user aren't readable.

**Comment by claudiux** [comment]
@Luiz-Trindade Each folder in your wallpaper path must be "readable and executable by other users". Your wallpaper itself must be "readable by other users". This may pose a security problem.
